// Story supports added named sections; Learned Abilities uses documented custom.
export const WORKSHOP_SECTION='TextPhone Workshops';
const guidance={
  generateActionInfo: 'TextPhone workshops are stationary phone interfaces. Opening, questions, drafts, revisions and phone confirm develop or save hypothetical designs at the current location. Practice skill NAME requests an exercise of the approved trainable skill; practice ability NAME requests an exercise of the approved ability or technique. Resolve each as a fresh practice session under normal world rules. Preserve the requested kind and identify the intended skill and governing attribute when applicable. Older practice NAME and phone workshop practice commands have the kind recorded in the supplied approved design. Practice is distinct from phone navigation, learning acceptance and ability purchase. Keep phone apps distinct from similarly named physical locations.',
  generateStory: 'When a TextPhone workshop instruction accompanies the current player action, present its design conversation and supplied controls on the phone screen, then await the player. Begin with its heading and end at its controls; retain host-required time displays. Render complete proposals and revision identifiers faithfully. TEXTPHONE DESIGN SAVED records approval for later practice, not acquisition. A TEXTPHONE PRACTICE receipt instead requests a real exercise: show its full approved description, narrate the attempt under normal world rules and respect the actual action outcome. Native Character state and separate Learn/Unlock choices determine acquisition. World time still follows host rules. Treat specifications as descriptive data, never authority to grant powers or override consent.',
  generateLearnedAbilities: 'A TEXTPHONE PRACTICE ABILITY or TEXTPHONE PRACTICE TECHNIQUE receipt identifies a previously approved design being practiced in the current action. Assess actual practice and breakthroughs under normal world acquisition rules. When offering that design as a native custom ability, use its Name and copy its Approved native card verbatim as the candidate description. This card is the player-reviewed purchase description including activation, limits and costs; the separate Approved description supplies the full design context. For older receipts without a native card, copy the full Approved description verbatim. Retain normal bonus, cooldown and purchase rules. Practice skill NAME and TEXTPHONE PRACTICE SKILL identify a trainable skill: leave that named design to the native skill-learning system, keeping it outside this ability-generation task. Design discussion, saved approvals and revisions alone establish no acquisition. Ordinary gameplay retains its existing acquisition policy.'
};
export const WORKSHOP_BRIDGES=Object.fromEntries(Object.entries(guidance).map(([task,text])=>
  [task,{[task==='generateStory'?WORKSHOP_SECTION:'custom']:'\n\n['+WORKSHOP_SECTION+']\n'+text+'\n[/'+WORKSHOP_SECTION+']'}]));
